---
# application.yml
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DotSpy/config-repo.git
#          username: trolley
#           password: strongpassword
#          basedir: build/cloud-configs
#          clone-on-start: true
#        git:
#          uri: https://github.com/DotSpy/by.bsuir.database
#        native:
#          search-locations: classpath:/shared


server:
  port: 8888